### PR TITLE
Dynamically updating Week Profile options via DynamicStateDescriptionProvider

### PR DESCRIPTION
**Pull request by espenaf**
Does not require manual setup of selection mapping anymore when using a DynamicStateDescriptionProvider to populate week profiles on the fly. This fixes the issues I had with exposing Week Profiles in a good way. Now the user can just edit them in the app, and get updates directly in the sitemap.

### CODE REVIEW

**Review by austvik — APPROVED** [review]
Really nice! This is starting to become advanced!

**Comment by austvik** [comment]
I have been running it here without any communication issues for three days now. Also running at your place, Espen? 

Should I try to rebase to 2.5.12 and 3.0.1, or do you have any other changes incoming that this could lead to a huge merge mess for?

**Comment by espenaf** [comment]
No more changes incoming right now, merge away.

**Comment by espenaf** [comment]
I have had no connectivity issues for the last weeks.

**Comment by austvik** [comment]
Strange to get this from something forked in github, I have started a support request on it.

git merge upstream/2.5.x
fatal: refusing to merge **unrelated histories**

**Comment by austvik** [comment]
Great, they have pruned history. Will ty to cherry-pick all changes.
https://github.com/openhab/openhab-addons/issues/5371

**Pull request merged**
